### ISSUE TITLE
Now that postgres has PROCEDUREs as well as FUNCTIONs ... can Fx?

### ISSUE THREAD

**Issue by redaikidoka** [teoljungberg/fx#125]
It would be amazing if fx supported procedures!

I would love to be able to say

`rails g fx:procedure my_fancy_procedure`

Because I accidentally tried to do that with a procedure and use `create_function` / `update_function` and boy did that not work (because of course it isn't supported yet).

I love this gem!

**Comment by teoljungberg** [comment]
I'm happy with the scope of the fx gem, and do not really want to add more postgres behaviors into it. I've already declined adding views (#69) because Scenic has support for it, and not wanting to include custom operators (#114) in favor of having it be a separate gem named `fx-operators` or similar.

I'd suggest the same procedure here, and whomever implements it - feel free to use fx's public API to make the work easier.

**Comment by sdhull** [comment]
FWIW we'd also be interested in support for stored procedures. I have zero idea how fx works internally so not sure what that lift would look like, but it _feels_ like it should be fairly straightforward. Right?

**Comment by redaikidoka** [comment]
This library is very well-made and well-structured, and does a bunch of things we didn't end up needing it to do like support rails generators, etc. 

We had a different idea of how we wanted versioning to work, so we decided to write replacement code for these functions ourselves.
 
My main concern was not being able to see the diffs for stored procedures, views, etc. in github reviews, so we changed things around so we have an unnumbered file that is updated, and then duplicated for versioning purposes, so you can look at for example, `my_fancy_view.sql` and see the changes in github, and essentially ignore `my_fancy_view_08.sql` as long as it's the same.

**Comment by sdhull** [comment]
@redaikidoka that sounds cool! I'm particularly interested in the diffs for PR reviews. Any code you can share?
