### ISSUE TITLE
create_function and create_trigger aren't reversible if given a version parameter

### ISSUE THREAD

**Issue by pjungwir** [teoljungberg/fx#16]
Hello, thanks for this gem!

The `create_function` and `create_trigger` commands both accept a `version` argument, but when you roll back the migration you get this failure, because `drop_function` and `drop_trigger` don't know about that param:

    ArgumentError: unknown keyword: version

(I'm not really sure why `create_` commands would need a version other than `1`, but I guess someone must be using it.)

I can see that you're already trying to make these commands reversible. Would you be interested in a PR that knows how to reverse creating functions & triggers when given a version? I guess it would still just `DROP` them.

**Comment by teoljungberg** [comment]
Hi!

I'm open for a PR fixing this, they should be reversible.

**Comment by teoljungberg** [comment]
Hi @pjungwir, sorry for taking so long to loop back to this. I haven't worked much on the project as it works flawlessly in the apps I work on a daily basis. So that there hasn't been any builds or work done is explained by that.

But yes, I do experience the same errors. As you said the default behavior seems to be to always add the qualified relation name, do you think it makes sense to update the test to reflect that? If so - how?

**Comment by teoljungberg** [comment]
Something like #19 should be sufficient. Let me know what you think.

**Comment by teoljungberg** [comment]
Echoing the comment I made in the PR:

https://github.com/teoljungberg/fx/pull/25#issuecomment-486963934
